# Note: Parameters can be hardcoded directly in '.github/workflows/deploy-functions.yaml'
# if you do not need to vary them between your functions!
common_folder: common
description: "Files contextualization Cognite function"
owner: project-ignis
cpu: "1"
memory: "1.5"
env_vars:
