# Note: Parameters can be hardcoded directly in '.github/workflows/deploy-functions.yaml'
# if you do not need to vary them between your functions!
common_folder: common
description: "Files contextualization Cognite function"
owner: project-ignis
cpu: 0.15
memory: 0.25
env_vars:

