- name: Norbis Park Schedule
  cron: "0 * * * *"
  data:
    assets_data_set_external_id: "src:njv:assets"
    files_data_set_external_id: "src:njv:limber"
    overwrite: True
    batch_size: -1

#- name: Kall Schedule
#  cron: "30 * * * *"
#  data:
#    assets_data_set_external_id: "src:kall:assets"
#    files_data_set_external_id: "src:kall:limber"
#    overwrite: True